Quiz.Web/Models/ErrorViewModel.cs
using System;

namespace Quiz.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Quiz.Web/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Quiz.Common.ViewModels;
using Quiz.Services.Interfaces;
using Quiz.Web.Models;
using ReflectionIT.Mvc.Paging;

namespace Quiz.Web.Controllers
{
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;
        private readonly IMapper mapper;
        private readonly IQuizService quizService;

        public MainController(ILogger<MainController> logger, IMapper mapper, IQuizService quizService)
        {
            this.mapper = mapper;
            this.quizService = quizService;
            _logger = logger;
        }


        public async Task<IActionResult> Index(int page = 1)
        {
            var quizzes = (await this.quizService.AllQuizzes())
                .Select(mapper.Map<AllQuizzesViewModel>);

            var pagedQuizzes = PagingList.Create(quizzes, 8, page);

            return this.View(pagedQuizzes);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Quiz.Web/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Quiz.Common.ViewModels;
using Quiz.Data.Models;
using Quiz.Services.Interfaces;

namespace Quiz.Web.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestionService questionService;
        private readonly IQuizService quizService;
        private readonly IMapper mapper;

        public QuestionController(IQuestionService questionService, IQuizService quizService, IMapper mapper)
        {
            this.questionService = questionService;
            this.quizService = quizService;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> AddQuestion()
        {
            var quizzes = (await this.quizService.AllQuizzes())
                .Select(mapper.Map<AllQuizzesViewModel>);

            ViewData["Quizzes"] = new SelectList(quizzes, "Id", "QuizName");

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddQuestion(AddQuestionBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            var question = mapper.Map<Question>(model);

            await this.questionService.AddQuestion(question);

            return RedirectToAction("Index", "Main", new { id = model.QuizId });
        }
    }
}

Quiz.Web/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Quiz.Services.Interfaces;
using Quiz.Common.ViewModels;
using Quiz.Data.Models;
using AutoMapper;
using Quiz.Services.ServiceModels;
using Microsoft.AspNetCore.Identity;

namespace Quiz.Web.Controllers
{
    public class QuizController : Controller
    {
        private readonly IQuizService quizService;
        private readonly IMapper mapper;
        //private readonly UserManager<UserAccount> userManager;


        public QuizController(IQuizService quizService, IMapper mapper)
        {
            this.quizService = quizService;
            this.mapper = mapper;
            //this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateQuiz()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateQuiz(CreateQuizBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            var quiz = mapper.Map<QuizGame>(model);

            await this.quizService.CreateQuiz(quiz);

            return RedirectToAction("Index", "Main");
        }
        
        public async Task<IActionResult> DeleteQuiz(int id)
        {
            await this.quizService.DeleteQuiz(id);

            return RedirectToAction("Index", "Main");
        }

        [HttpGet]
        public async Task<IActionResult> StartQuiz(int id)
        {
            var getQuiz = await this.quizService.GetQuizById(id);
            var jsonData = await this.quizService.GetJsonQuizById(id);

            var quiz = mapper.Map<QuizViewModel>(getQuiz);

            if (quiz == null)
            {
                return this.View();
            }
            ViewData["jsonData"] = jsonData;
            return this.View(quiz);
        }

        [HttpGet]
        public IActionResult Settings()
        {            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Settings(UserBindingModel model)
        {
            //var currentUser = await userManager.GetUserAsync(User);

            if (!ModelState.IsValid)
            {
                return this.View();
            }
            //currentUser.Mode = model.Mode;

            //await this.quizService.UserSettings(currentUser);

            return RedirectToAction("Index", "Main");
        }
    }
}

Quiz.Web/Views/Main/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<AllQuizzesViewModel>
@using ReflectionIT.Mvc.Paging
@using Quiz.Common.ViewModels
@addTagHelper *, ReflectionIT.Mvc.Paging
@{ ViewData["Title"] = "Main Page"; }

<div class="row mx-auto">
    @if (Model.Count() == 0)
    {
<div class="mx-auto card-holder">
    <div class="quizCard text-center" style="width: 20em;">
        <p>No quizzes yet.</p>
        <a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="CreateQuiz" title="Create Quiz"><i class="icon fas fa-plus-square fa-2x" style="color: white"></i></a>
    </div>
</div> }
else
{
@foreach (var quiz in Model)
{
<div class="col-md-4">
    <div class="card" style="margin-top: 30px;">
        <div class="card-body">
            <h4>@quiz.QuizName </h4>
            <h5>@quiz.Mode </h5>
            @if (@quiz.QuizQuestions.Count == 0)
            {
    <p>No questions yet</p> }
else if (@quiz.QuizQuestions.Count == 1)
{
    <p>@quiz.QuizQuestions.Count question</p> }
else
{
    <p>@quiz.QuizQuestions.Count questions</p>}
        </div>
        <div>
            <div style="margin: 10px; text-align: center;">
                @*<a style="padding: 10px;" asp-action="StartQuiz" asp-controller="Quiz" asp-route-id="@quiz.Id" title="Start">Start</a>*@
                <a type="button" class="btn btn-success" asp-action="StartQuiz" asp-controller="Quiz" asp-route-id="@quiz.Id" title="Start">Start</a>

                @*<a style="padding: 10px;" asp-action="DeleteQuiz" asp-controller="Quiz" asp-route-id="@quiz.Id" title="Delete">Delete</a>*@
            <a type="button" class="btn btn-warning" asp-action="DeleteQuiz" asp-controller="Quiz" asp-route-id="@quiz.Id" title="Delete">Delete</a>

            </div>
        </div>
        </div>
    </div>}}
</div>
<div>
    <nav>
        @Html.Partial("PagerOptions", this.Model)
    </nav>
</div>

Quiz.Web/Views/Question/AddQuestion.cshtml
@using Quiz.Common.ViewModels
@using Quiz.Data.Models.Enums
@model AddQuestionBindingModel

<style>
    .btn-transparent {
        background-color: transparent;
        border: none;
    }
</style>

<div class="row">
    <div class="mx-auto">

        <form id="addQuestionForm" asp-controller="Question" asp-action="AddQuestion" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mx-auto card-holder">
                <div class="quizCard text-left" style="width: 20em;">
                    <div class="">
                        <label asp-for="QuestionName" class="control-label">Question</label>
                        <input asp-for="QuestionName" class="form-control" />
                        <span asp-validation-for="QuestionName" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="FirstAnswer">First Option</label>
                        <input asp-for="FirstAnswer" class="form-control" />
                    </div>
                    <div>
                        <label asp-for="SecondAnswer">Second Option</label>
                        <input asp-for="SecondAnswer" class="form-control" />
                    </div>
                    <div>
                        <label asp-for="ThirdAnswer">Third Option</label>
                        <input asp-for="ThirdAnswer" class="form-control" />
                    </div>
                    <hr />
                    <div>
                        <label asp-for="CorrectAnswerIndex">Correct Answer</label>
                        <select class="custom-select" asp-for="CorrectAnswerIndex" asp-items="Html.GetEnumSelectList<CorrectAnswer>()">
                            <option selected="selected" value="@CorrectAnswer.None">Select the correct answer</option>
                        </select>
                        <span asp-validation-for="CorrectAnswerIndex" class="text-danger"></span>
                    </div>
                    <hr />
                    <div>
                        <label class="screen-reader-only" for="choice">Correct Binary Answer?</label>
                        <label>
                            <input type="radio" asp-for="BinaryAnswer" name="choice-radio" value="true" checked="checked">
                            Yes
                        </label>
                        <label>
                            <input type="radio" asp-for="BinaryAnswer" name="choice-radio" value="false">
                            No
                        </label>
                    </div>
                    <hr />
                    <div>
                        <label>Multiple choice question mode</label>
                        <input class="screen-reader-only" id="MultipleChoiceMode" asp-for="MultipleChoiceMode" type="radio" value="true" checked="checked" />
                        <label class="form-check-label" for="AffectsUsersYes">Yes</label>
                    </div>
                    <hr />
                    <div class="form-group">
                        <label asp-for="QuizId" class="control-label">Quiz</label>
                        <select asp-for="QuizId" class="form-control" asp-items="ViewBag.Quizzes">
                        </select>
                    </div>
                    <div class="text-center">
                        <button class="btn btn-light" type="submit">Save Question</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Quiz.Web/Views/Quiz/CreateQuiz.cshtml
@model CreateQuizBindingModel
@using Quiz.Data.Models.Enums
@using Quiz.Common.ViewModels

@{
    ViewData["Title"] = "CreateQuiz";
}

<style>
    .btn-transparent {
        background-color: transparent;
        border: none;
    }
</style>

<div class="row">
    <div class="mx-auto">

        <form id="createQuizForm" asp-controller="Quiz" asp-action="CreateQuiz" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mx-auto card-holder">
                <div class="quizCard text-left" style="width: 20em;">
                    <div class="form-group">
                        <label asp-for="QuizName" class="control-label">Quiz Name</label>
                        <input asp-for="QuizName" class="form-control" />
                        <span asp-validation-for="QuizName" class="text-danger"></span>
                    </div>
                    <div>
                        <label asp-for="Mode">Category</label>
                        <select class="custom-select" asp-for="Mode" asp-items="Html.GetEnumSelectList<ApplicationMode>()">
                            <option selected="selected" value="">Select category</option>
                        </select>
                        <span asp-validation-for="Mode" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="text-center">
                        <button class="btn btn-light" type="submit">Save Quiz</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Quiz.Web/Views/Quiz/Settings.cshtml
@model UserBindingModel
@using Quiz.Common.ViewModels
@using Quiz.Data.Models.Enums

<div class="row">
    <div class="mx-auto">

        <form id="createQuizForm" asp-controller="Quiz" asp-action="Settings" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mx-auto card-holder">
                <div class="quizCard text-left" style="width: 20em;">
                    <div>
                        <label asp-for="Mode">Quiz Mode</label>
                        <select class="custom-select" asp-for="Mode" asp-items="Html.GetEnumSelectList<ApplicationMode>()">
                            <option selected="selected" value="">Select mode</option>
                        </select>
                        <span asp-validation-for="Mode" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="text-center">
                        <button class="btn btn-light" type="submit">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Quiz.Web/Views/Quiz/StartQuiz.cshtml
@model QuizViewModel
@using Quiz.Common.ViewModels

@{ ViewData["Title"] = "StartQuiz";
    var json = ViewData["jsonData"].ToString(); }



<div id="quiz">
    <div id="quiz-header">
        <h1 id="quiz-logo">@Model.QuizName</h1>
        <p><a id="quiz-home">Questions Mode : @Model.Mode</a></p>
    </div>
    <div id="quiz-start-screen">
        <div><a href="#" id="quiz-start-btn" class="quiz-button">Click to Start</a></div>
    </div>
</div>


<script>

    var questions = '@json';
    var data = questions.replace(new RegExp("&" + "#" + "x27;", "g"), "'");

    // Variable to keep track of the total score.
    var totalScore = 0;

    // Provide an answer callback to add points to the score if correct answer selected.
    var answerCallback = function (currentQuestion, selected, question) {
        // Check if the user got the answer correct.
        if (selected === question.correctIndex) {
            // Add the points as specified in the question parameters, or default to 1.
            totalScore += question.points || 1;
        }
    };

    // Provide a callback to reset the score. Used if the home button is clicked.
    var resetScore = function () {
        totalScore = 0;
    };  

    // Provide a finish callback to display the score.
    var finishCallback = function () {
        $('#quiz-results').html('Total Score: ' + totalScore + ' Points');
        // Be sure to reset the score.
        totalScore = 0;
    };

    $('#quiz').quiz({
        homeButton: '#quiz-home',
        // Specify answer callback.
        answerCallback: answerCallback,
        // Specify finish callback.
        finishCallback: finishCallback,
        // Specify callback to reset score.
        homeCallback: resetScore,
        questions: 
            [
                {
                    'q': 'Is jQuery required for this plugin?',
                    'options': [
                        'Yes',
                        'No'
                    ],
                    'correctIndex': 0,
                    'correctResponse': 'Good job, that was obvious.',
                    'incorrectResponse': 'Well, if you don\'t include it, your quiz won\'t work'
                },
                {
                    'q': 'How do you use it?',
                    'options': [
                        'Include jQuery, that\'s it!',
                        'Include jQuery and the plugin javascript.',
                        'Include jQuery, the plugin javascript, the optional plugin css, required markup, and the javascript configuration.'
                    ],
                    'correctIndex': 2,
                    'correctResponse': 'Correct! Sounds more complicated than it really is.',
                    'incorrectResponse': 'Come on, it\'s not that easy!'
                },
                {
                    'q': 'The plugin can be configured to require a perfect score.',
                    'options': [
                        'True',
                        'False'
                    ],
                    'correctIndex': 0,
                    'correctResponse': 'You\'re a genius! You just set allowIncorrect to true.',
                    'incorrectResponse': 'Why you have no faith!? Just set allowIncorrect to true.'
                },
                {
                    'q': 'How do you specify the questions and answers?',
                    'options': [
                        'MySQL database',
                        'In the HTML',
                        'In the javascript configuration'
                    ],
                    'correctIndex': 2,
                    'correctResponse': 'Correct! Refer to the documentation for the structure.',
                    'incorrectResponse': 'Wrong! Do it in the javascript configuration. You might need to read the documentation.'
                }
            ]
    });
</script>





































@*<style>
        .bg-quizLogo {
            color: #fff;
            background: linear-gradient(-70deg, #045de9 0%, rgba(0, 0, 0, 0) 74%), url('@Model.QuizLogoUrl');
            background-repeat: no-repeat;
            background-size: contain;
            text-align: right;
            border-top-right-radius: 1em;
            border-bottom-right-radius: 1em;
        }
    </style>




    <br />
    <div class="text-center">
        <div class="quizLogoCard bg-quizLogo text-dark">
            <h3>@Model.QuizName</h3><h5>@Model.Mode</h5>
        </div>
    </div>
    <hr />

    @{ var questions = Model.QuizQuestions as QuestionViewModel[] ?? Model.QuizQuestions.ToArray(); }
    <div class="row">
        <div class="mx-auto">

            @if (Model.QuizQuestions.Count() == 0)
            {
    <div class="mx-auto card-holder">
        <div class="quizCard text-center" style="width: 20em;">
            <p>No questions yet.</p>
            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="AddQuestion" title="Add Question"><i class="icon fas fa-question-circle fa-2x" style="color: white"></i></a>
        </div>
    </div> }
                else
                {
    <form asp-controller="Quiz" asp-action="StartQuiz" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @for (var i = 0; i < questions.Length; i++)
        {
    <div class="mx-auto card-holder">
        <div class="quizCard text-left" style="width: 20em;">
            <h4 class="text-center">@questions[i].QuestionName</h4>

            <input type="hidden" asp-for="Answers[i].QuestionId" value="@questions[i].Id" />
            <div>
                <input type="radio" asp-for="Answers[i].Answer" value="@questions[i].FirstAnswer" />
                <label>A @questions[i].FirstAnswer</label>
            </div>
            <div>
                <input type="radio" asp-for="Answers[i].Answer" value="@questions[i].FirstAnswer" />
                <label>B @questions[i].SecondAnswer</label>
            </div>
            <div>
                <input type="radio" asp-for="Answers[i].Answer" value="@questions[i].ThirdAnswer" />
                <label>C @questions[i].ThirdAnswer</label>
            </div>
        </div>
    </div>                }
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-style">
                        <h5 class="modal-title" id="exampleModalLongTitle">Finish</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        After clicking "Submit" you will see your results.
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Return</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
                    <div>
                        <button class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalCenter">Finish</button>
                    </div>}
        </div>
    </div>*@

Quiz.Web/Views/Shared/PagerOptions.cshtml
@model ReflectionIT.Mvc.Paging.IPagingList
@* Boostrap 4 based pager *@

@{
    var start = this.Model.StartPageIndex;
    var stop = this.Model.StopPageIndex;
}
<style>
    .icon:hover {
        text-shadow: 0 0 5px #000;
        transform: scale(1.5);
    }   
</style>
@if (this.Model.PageCount > 1)
{
    <ul class="pagination pagination-lg justify-content-center">


        @if (this.Model.PageIndex == 1)
        {
            <li class="page-item disabled card-holder">
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex - 1))" aria-label="Previous" class="page-link" style="background-color: transparent">
                    <i class="icon fa fa-chevron-left" style="color: white" aria-hidden="true"></i>
                </a>
            </li>
        }
        else
        {
            <li class="page-item card-holder">
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex - 1))" aria-label="Previous" class="page-link" style="background-color: transparent">
                    <i class="icon fa fa-chevron-left" style="color: white" aria-hidden="true"></i>
                </a>
            </li>
        }

        @if (this.Model.PageIndex == this.Model.PageCount)
        {

            <li class="page-item disabled card-holder">
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex + 1))" aria-label="Next" class="page-link" style="background-color: transparent;">
                    <i class="icon fa fa-chevron-right" style="color: white" aria-hidden="true"></i>
                </a>
            </li>
        }
        else
        {
            <li class="page-item card-holder">
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex + 1))" aria-label="Next" class="page-link" style="background-color: transparent">
                    <i class="icon fa fa-chevron-right" style="color: white" aria-hidden="true"></i>
                </a>
            </li>
        }
    </ul>
}

Quiz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Quiz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="~/js/jquery.quiz-min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Index">Quiz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Index">Main</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="Settings">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="CreateQuiz">Create Quiz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="AddQuestion">Add Question</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Quiz - Hristo Hristov
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src='https://jchamill.github.io/jquery-quiz/jquery.quiz-min.js'></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>